server:
  port: 8282
spring:
  data:
    elasticsearch:
      cluster-name: my-application #默认即为 elasticsearch
      cluster-nodes: 192.168.14.51:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      repositories:
        enabled: true
